osx_image: xcode8.2
language: objective-c

before_install:
  # Fix Travis  xcodebuild exited with 65 https://github.com/travis-ci/travis-ci/issues/6675#issuecomment-257964767
  - export IOS_SIMULATOR_UDID=`instruments -s devices | grep -m 1 "iPhone 6 (10.2" | awk -F '[ ]' '{print $4}' | awk -F '[\[]' '{print $2}' | sed 's/.$//'`
  - echo $IOS_SIMULATOR_UDID
  - open -a "simulator" --args -CurrentDeviceUDID $IOS_SIMULATOR_UDID

install:
  - cd Tests
  - bundle install
  - bundle exec pod install --project-directory=./iOS
  - bundle exec pod install --project-directory=./Mac
  - cd ../

script:
  - set -o pipefail
  - travis_retry xcodebuild -workspace ./Tests/iOS/CocoaAsyncSocket.xcworkspace -scheme CocoaAsyncSocketTestsiOS -sdk iphonesimulator -destination "id=$IOS_SIMULATOR_UDID" test | xcpretty -c
  - xcodebuild -workspace ./Tests/Mac/CocoaAsyncSocket.xcworkspace -scheme CocoaAsyncSocketTestsMac -sdk macosx -destination 'platform=OS X,arch=x86_64' test | xcpretty -c
  - xcodebuild -project Tests/Framework/CocoaAsyncSocketTests.xcodeproj -scheme "CocoaAsyncSocketTests (iOS)" -sdk iphonesimulator -destination "id=$IOS_SIMULATOR_UDID" test | xcpretty -c
  - xcodebuild -project Tests/Framework/CocoaAsyncSocketTests.xcodeproj -scheme "CocoaAsyncSocketTests (macOS)" -sdk macosx -destination 'platform=OS X,arch=x86_64' test | xcpretty -c
