osx_image: xcode11.3
language: objective-c

install:
  - cd Tests
  - bundle install
  - bundle exec pod install --project-directory=./iOS
  - bundle exec pod install --project-directory=./Mac
  - cd ../

script:
  - export IOS_VERSION="11.2" # waiting for xcode9.3 on Travis
  - bash Tests/test-all.sh
  - swift build
